### ISSUE TITLE
无法导入 txt，建议支持本地 text 导入，进一步可以封装为 pod 库

### ISSUE THREAD

**Issue by shang1219178163** [ZhongshanHuang/PoReader#1]
![IMG_57C8706E9DE3-1](https://user-images.githubusercontent.com/3699729/87262440-87ecf200-c4ec-11ea-9bff-b8d78c0d0e20.jpeg)
qq 浏览器的小说阅读模块是我用过体验最好的，自定义背景是核心功能

**Comment by shang1219178163** [comment]
网络问题，请忽略

**Comment by ZhongshanHuang** [comment]
> ![IMG_57C8706E9DE3-1](https://user-images.githubusercontent.com/3699729/87262440-87ecf200-c4ec-11ea-9bff-b8d78c0d0e20.jpeg)
> qq 浏览器的小说阅读模块是我用过体验最好的，自定义背景是核心功能

qq阅读器的体验是我用过最好的，但是后来广告越来越多。。。自定义背景最开始写的时候是支持的，但是它与系统的暗黑模式是有冲突的，我为了练手暗黑模式就将自定义背景去掉了
